import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const shinShin = localFont({
  src: "./ShinShin.woff2",
  display: "swap"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={shinShin.className}>{children}</body>
    </html>
  )
}
